// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSensorAccelChange();
void onSensorSoundChange();
void onSensorTempChange();
void onTimestampSecChange();
void onLedControlChange();

float sensorAccel;
float sensorSound;
float sensorTemp;
float timestampSec;
bool ledControl;

void initProperties(){

  ArduinoCloud.addProperty(sensorAccel, READWRITE, ON_CHANGE, onSensorAccelChange);
  ArduinoCloud.addProperty(sensorSound, READWRITE, ON_CHANGE, onSensorSoundChange);
  ArduinoCloud.addProperty(sensorTemp, READWRITE, ON_CHANGE, onSensorTempChange);
  ArduinoCloud.addProperty(timestampSec, READWRITE, ON_CHANGE, onTimestampSecChange);
  ArduinoCloud.addProperty(ledControl, READWRITE, ON_CHANGE, onLedControlChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
